* About

The R-package =rtmle= implements a class of targeted minimum loss
estimators for the analysis of longitudinal register data. The
functionality is similar to the established R-package =ltmle= with the
following features and focus points:

- explicit handling of competing risks
- polypharmacy
- descriptive statistics
- diagnostic tools (not to be confused with model goodness of fit)
- subgroup analysis
- support for glmnet
- cheap bootstrap inference
- cross-fitting 
- parallel computing

* Data structures  

We consider register data in the following format.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes
library(rtmle)
library(prodlim)
library(riskRegression)
library(data.table)
set.seed(118)
ld <- simulate_long_data(n = 10000,number_epochs = 20,beta = list(sum_A_on_Y = -.1,A0_on_Y = 0),register_format = TRUE)
ld
#+END_SRC

#+RESULTS[(2024-10-03 16:28:18) c882943695f57f545c4d35bcaa06c480ca36b3a8]:
:results:
$baseline_data
          id   sex      age
       <int> <int>    <num>
    1:     1     0 59.44409
    2:     2     1 73.01360
    3:     3     0 78.26086
    4:     4     1 66.53408
    5:     5     0 62.35921
   ---                     
 9996:  9996     0 43.90035
 9997:  9997     1 41.32339
 9998:  9998     0 65.08893
 9999:  9999     1 42.23665
10000: 10000     1 57.38959

$timevar_data
$timevar_data$L
         id   date
      <int>  <num>
   1:     1   0.00
   2:     3   0.00
   3:     5   0.00
   4:     8   0.00
   5:    14   0.00
  ---             
5119:  9988 421.80
5120:  9992 355.43
5121:  9995 246.33
5122:  9998 377.86
5123:  9998 483.76

$timevar_data$A
         id  date
      <int> <num>
   1:     1     0
   2:     3     0
   3:     5     0
   4:     7     0
   5:     9     0
  ---            
5249:  9590   365
5250:  9671   365
5251:  9694   365
5252:  9859   365
5253:  9984   730


$outcome_data
         id    date
      <int>   <num>
   1:     1 1076.89
   2:     3   50.49
   3:     6  140.84
   4:     7  402.61
   5:    11  481.58
  ---              
3341:  9979   60.41
3342:  9990   31.30
3343:  9993   19.82
3344:  9998  609.26
3345:  9999    8.99

$competing_data
         id   date
      <int>  <num>
   1:     4  89.71
   2:     8  91.81
   3:    10 545.28
   4:    13 446.94
   5:    14 459.49
  ---             
3360:  9987  30.28
3361:  9988 476.90
3362:  9994 311.22
3363:  9996  71.81
3364:  9997 179.60

$censored_data
         id    date
      <int>   <num>
   1:     2  260.64
   2:     5    6.32
   3:     9  209.74
   4:    25  298.93
   5:    33  341.00
  ---              
3287:  9989   53.65
3288:  9991  392.38
3289:  9992 1046.23
3290:  9995  758.63
3291: 10000  140.10
:end:

* Example


** Initializing


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer :exports both  :session *R* :cache yes  
x <- rtmle_init(intervals = 3,name_id = "id",name_outcome = "Y",name_competing = "Dead",name_censoring = "Censored",censored_label = "censored")
x
#+END_SRC

#+RESULTS[(2024-10-03 16:28:18) 8b507b232db5bb073a8147380c6d781f9e76f9f1]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no data yet. Add them with the functions 'add_register_data<-' and 'add_data<-'.
TODO: The object contains no protocols. Add them with the function 'protocol<-'.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Adding the data

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
x$long_data <- ld[c("outcome_data","censored_data","competing_data","timevar_data")]
add_baseline_data(x) <- ld$baseline_data[,start_followup_date:=0]
x
#+END_SRC

#+RESULTS[(2024-10-03 16:28:18) baab07cfaaf782a112f2659e6a4ba4dd791d5050]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no protocols. Add them with the function 'protocol<-'.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Preparing the data

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
x <- long_to_wide(x,intervals = seq(0,2000,30.45*6))
prepare_data(x) <- list()
#+END_SRC

#+RESULTS[(2024-10-03 16:28:20) a3b2259f4fbd1a6505a368eec81f685182ce33b6]:
:results:
:end:


** Defining the protocols

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
protocol(x) <- list(name = "always A",treatment_variables = "A",intervention = 1)
protocol(x) <- list(name = "never A",treatment_variables = "A",intervention = 0)
x
#+END_SRC

#+RESULTS[(2024-10-03 16:28:20) b573ac1575eb7a69bf7d0c058328d423181f467f]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Defining the targets

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
target(x) <- list(name = "Outcome_risk",strategy = "additive",estimator = "tmle",time_horizon = 3,protocols = c("always A","never A"))
target(x) <- list(name = "Outcome_risk_g",strategy = "additive",estimator = "g",time_horizon = 3,protocols = c("always A","never A"))
x
#+END_SRC

#+RESULTS[(2024-10-03 16:28:20) e10547eb4a9d4e196a8b46472920dd0a1fd24c68]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
:end:


** Sequential regression with and without TMLE update step

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer :exports both  :session *R* :cache yes
x <- run_rtmle(x,learn = "learn_glm")
summary(x)
#+END_SRC

#+RESULTS[(2024-10-03 16:28:21) 2ba32a24f4c0bcf2c0fd1e66163ca03fff3cfca9]:
:results:
Running target: Outcome_risk
Current protocol: always A
Current protocol: never A
Error: No method available for evaluating predicted probabilities from objects in class: NULL. But, you can write it yourself or ask the package manager.
In addition: Warning messages:
1: glm.fit: algorithm did not converge 
2: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
3: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
4: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
5: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
6: In eval(family$initialize) : non-integer #successes in a binomial glm!
7: In predict.lm(object, newdata, se.fit, scale = 1, type = if (type ==  :
  prediction from rank-deficient fit; attr(*, "non-estim") has doubtful cases
8: In eval(family$initialize) : non-integer #successes in a binomial glm!
Error: Check that is.data.table(DT) == TRUE. Otherwise, :=, `:=`(...) and let(...) are defined for use in j, once only and in particular ways. See help(":=").
:end:


#+TITLE: Introduction to the R-package rtmle
#+Author: Thomas Alexander Gerds
#+Date: 
#+EMAIL: tag@biostat.ku.dk
#+LaTeX_CLASS: org-article
#+OPTIONS: H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\author{Thomas Alexander Gerds}
#+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen}
#+set: superman-org-export-target: html

