#+TITLE: Transforming long register data to time-discretized wide data using build-in rtmle tools
#+Author: Anders Munch
#+Date: August 21, 2026 
#+LaTeX_CLASS: org-article
#+OPTIONS: H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:nil
#+PROPERTY: header-args:R :async :results output verbatim :exports both :session *R* :cache no

* Aim
This vignette...

TEST:

#+BEGIN_SRC R
9+9
#+END_SRC

#+RESULTS:
: [1] 18

#+BEGIN_SRC R :results output drawer
9+9
#+END_SRC

#+RESULTS:
:results:
[1] 18
:end:

* Preparation
Here, we prepare a simulated dataset of synthetic EHR on long format,
initiate the =rtmle= object, and add the long data to =rtmle=
object. See [[./register-tmle-simulated-cohort.org]] for details about the
data format and initialization of the =rtmle= object.

#+BEGIN_SRC R
  ## Load packages
  library(rtmle)
  library(data.table)

  ## Load data, put on register format, and fix date naming
  data(simulated_cohort)
  ld <- register_format(simulated_cohort)

  ## Construct exposure like format
  setorder(ld$timevar_data$A, id, date)

  ld$timevar_data$exposure <- ld$timevar_data$A[value == 1,
    .(start_date = first(date), end_date = last(date)),
    by = .(id, run = rleid(value))
  ][, run := NULL]

  ## Initialize rtmle object
  x <- rtmle_init(
      time_grid = seq(0, 20, 4),
      name_id = "id",
      name_outcome = "stroke",
      name_competing = "death",
      name_censoring = "dropout",
      censored_label = "censored"
  )

  ## Add baseline and time-varying data to the rtmle object
  x <- add_baseline_data(x, data = ld$baseline_data)
  x <- add_long_data(
      x,
      outcome_data = ld$timevar_data$stroke[!duplicated(id)],
      censored_data = ld$timevar_data$dropout,
      competing_data = ld$timevar_data$death,
      timevar_data = ld$timevar_data[c("bleeding", "changeSBP", "exposure")]
  )

  x
#+END_SRC

#+RESULTS:
#+begin_example

Targeted minimum loss-based analysis of longitudinal data on a discretized time scale.

Package version:     2026.5.28
Subject id variable: id
Outcome variable:    stroke
Censoring variable:  dropout
Competing risk:      death
Intervention nodes:  0, 1, 2, 3, 4
Minority threshold:  8
Weight truncation:   (0,1)
Prediction range:    (0.0001,0.9999)
Baseline data:       n=307, p=3
TODO: The object contains no time varying data yet. Add them with rtmle::add_wide_data in discretized form or with rtmle::add_long_data followed by rtmle::long_to_wide.
TODO: The object contains no outcome data yet. Add them with rtmle::add_wide_data in discretized form or with rtmle::add_long_data followed by rtmle::long_to_wide.
TODO: The object contains no protocols. Add them with the function 'protocol'.
Prepared data:       n=0, p=-1
TODO: Use the function 'model_formula' to initialize the formula for the nuisance parameter models.
TODO: Use the function 'run_rtmle' to estimate the nuisance parameter models and the target parameter.
Diagnostics:         No warnings (yet)
#+end_example

* =long_to_wide= mappings

The function =long_to_wide= converts long data from registers into
wide format data based on the =time_grid= specified in
=rtmle_init=. This transformation can be done in many different ways,
and the function supplies some commonly used methods. Which methods
can be used, depend on the data format. In the current =rtmle= object
=x=, we have three different formats stored. The variables names
should be as below for the methods to work.

- Time of event :: The data contains times at which an event happened:

  #+BEGIN_SRC R
    head(x$long_data$timevar_data$bleeding)
  #+END_SRC

  #+RESULTS[ac47658e9506cadc954bf643f49df4784540832b]:
  :       id      date
  :    <int>     <num>
  : 1:     1  3.873840
  : 2:     2 17.621493
  : 3:     4 17.012149
  : 4:     5 10.010786
  : 5:     5 12.021059
  : 6:     6  1.497292

- Measurement :: The data contains a date at which a measurement is
  made and the value of that measurement:

  #+BEGIN_SRC R
    head(x$long_data$timevar_data$changeSBP)
  #+END_SRC

  #+RESULTS[63d7fe2adfbdaf9bc64159c5b88178d78fe01020]:
  : Key: <id, date>
  :       id    date      value
  :    <int>   <num>      <num>
  : 1:     1 0.00000  0.0000000
  : 2:     1 1.12419  0.1784864
  : 3:     1 2.12419 -1.0567860
  : 4:     1 3.12419 -1.3952744
  : 5:     1 4.87384  1.5401140
  : 6:     2 0.00000  0.0000000

- Duration :: The data contains start and end times of some exposure:

  #+BEGIN_SRC R
    head(x$long_data$timevar_data$exposure)
  #+END_SRC

  #+RESULTS[980315a3614d124e843c74e755a2ca77461365b9]:
  :       id start_date  end_date
  :    <int>      <num>     <num>
  : 1:     1   1.124190  4.873840
  : 2:     2   2.156835 19.659187
  : 3:     3   3.133106 19.551143
  : 4:     4   4.105284 19.088166
  : 5:     5   0.000000 17.030020
  : 6:     6   0.000000  4.062148

The function =long_to_wide= will attempt to guess default methods
based on the data format of each of the variables supplied to the
=timevar_data= argument of =add_long_data=. The code is easier to
understand when we instead explicitly specify the method, e.g., as
follows:

#+BEGIN_SRC R
x <- long_to_wide(x,
                  bleeding = list(method = "event"),
                  changeSBP = list(method="locf"),
                  exposure = list(method = "any_exposure"))
#+END_SRC

#+RESULTS[75f120bb609e14c80670a14b1974a7a7543ad801]:

We describe each of these methods and all the others below. The
example above construct data sets that look as this:

#+BEGIN_SRC R
lapply(x$data$timevar_data, head)
#+END_SRC

#+RESULTS[7be78f4cf5fb185bebdc90ad64699bc81d8a5487]:
#+begin_example
$bleeding
Key: <id>
      id bleeding_0 bleeding_1 bleeding_2 bleeding_3 bleeding_4 bleeding_5
   <int>      <num>      <num>      <num>      <num>      <num>      <num>
1:     1          0          1          1         NA         NA         NA
2:     2          0          0          0          0          0          1
3:     3          0          0          0          0          0          0
4:     4          0          0          0          0          0          1
5:     5          0          0          0         NA         NA         NA
6:     6          0          1         NA         NA         NA         NA

$changeSBP
Key: <id>
      id changeSBP_0 changeSBP_1 changeSBP_2 changeSBP_3 changeSBP_4 changeSBP_5
   <int>       <num>       <num>       <num>       <num>       <num>       <num>
1:     1           0  -1.3952744   1.5401140          NA          NA          NA
2:     2           0   0.1478189   0.2222623   0.7055493 -0.59657268  -0.1934477
3:     3           0   0.1659106  -0.4327238   0.5363959  0.68536226  -0.3657148
4:     4           0  -1.1259092  -0.8309444  -1.3322135  0.06677293  -0.4016678
5:     5           0  -0.6132105  -0.8440525          NA          NA          NA
6:     6           0  -1.3340647          NA          NA          NA          NA

$exposure
Key: <id>
      id exposure_0 exposure_1 exposure_2 exposure_3 exposure_4 exposure_5
   <int>      <num>      <num>      <num>      <num>      <num>      <num>
1:     1          0          1          1         NA         NA         NA
2:     2          0          1          1          1          1          1
3:     3          0          1          1          1          1          1
4:     4          0          0          1          1          1          1
5:     5          1          1          1         NA         NA         NA
6:     6          1          1         NA         NA         NA         NA
#+end_example

We can use different methods to construct different wide format
variables from the same long format variable by setting the =variable=
argument:

#+BEGIN_SRC R
  x <- long_to_wide(x,
		    exposure_any = list(variable = "exposure", method = "any_exposure"),
		    exposure_percent = list(variable = "exposure", method = "exposure_percent"))
  lapply(x$data$timevar_data[c("exposure_any", "exposure_percent")], head)
#+END_SRC

#+RESULTS:
#+begin_example
$exposure_any
Key: <id>
      id exposure_any_0 exposure_any_1 exposure_any_2 exposure_any_3 exposure_any_4
   <int>          <num>          <num>          <num>          <num>          <num>
1:     1              0              1              1             NA             NA
2:     2              0              1              1              1              1
3:     3              0              1              1              1              1
4:     4              0              0              1              1              1
5:     5              1              1              1             NA             NA
6:     6              1              1             NA             NA             NA
   exposure_any_5
            <num>
1:             NA
2:              1
3:              1
4:              1
5:             NA
6:             NA

$exposure_percent
Key: <id>
      id exposure_percent_0 exposure_percent_1 exposure_percent_2 exposure_percent_3
   <int>              <num>              <num>              <num>              <num>
1:     1                  0          0.7189525           0.218460                 NA
2:     2                  0          0.4607913           1.000000                  1
3:     3                  0          0.2167236           1.000000                  1
4:     4                  0          0.0000000           0.973679                  1
5:     5                  1          1.0000000           1.000000                 NA
6:     6                  1          1.0000000                 NA                 NA
   exposure_percent_4 exposure_percent_5
                <num>              <num>
1:                 NA                 NA
2:                  1          0.9147968
3:                  1          0.8877856
4:                  1          0.7720416
5:                 NA                 NA
6:                 NA                 NA
#+end_example

The methods than can be used for each of the data formats are:

- Time of event ::
  - =event= :: Indicates whether the event has ever occurred
  - =time_since_event= :: Gives the time since last event
  - =event_interval= :: Indicates whether the event occurred within
    the preceding interval.

- Measurement ::
  - =locf= :: Last observation carried forward -- records the last
    value prior to the current time point.
  - =measurement= :: Construct univariate summary from the
    observations in the preceding interval using specified function
    that can be supplied with the =fun_aggregate= argument. The
    default function is to use the last value. To use, e.g., the mean
    instead, we can do

    #+BEGIN_SRC R
      x <- long_to_wide(x, changeSBP_mean=list(variable = "changeSBP", method="measurement",fun_aggregate="mean"))
    #+END_SRC

    #+RESULTS[bc99d5715335937e28fc4edf065c8baca381771a]:
    : 57bfd5010a2bdf198e0f930d5a8672d8

- Duration ::
  - =any_exposure= :: Indicates whether the subject has been exposed
    in the previous interval.
  - =has_exposure= :: Indicates whether the subject has been exposed
    for longer than =threshold= time in the previous interval
    (equivalent to =any_exposure= when ~threshold=0~).
  - =exposure_time= :: The time that the subject has been exposed in
    the previous interval.
  - =exposure_percent= :: The percentage of the time that the subject
    has been exposed in the previous interval.
    
  We illustrate the methods here, using ~threshold=2~. As the grid is
  equidistant with intervals equal to 4, this mean that wide variables
  =exposure_threshold_0=, =exposure_threshold_1=, ..., indicate
  whether the subject have been exposed at least half of the previous
  interval.

  #+BEGIN_SRC R
    x <- long_to_wide(x,
		      exposure_any = list(variable = "exposure", method = "any_exposure"),
		      exposure_percent = list(variable = "exposure", method = "exposure_percent"),
		      exposure_time = list(variable = "exposure", method = "exposure_time"),
		      exposure_threshold = list(variable = "exposure", method = "has_exposure", threshold = 2))
    lapply(x$data$timevar_data[paste0("exposure_", c("any", "percent", "time", "threshold"))], head)
  #+END_SRC

  #+RESULTS[4b70352a6dd83381e729d1a99e938cbe7a938b62]:
  #+begin_example
  $exposure_any
  Key: <id>
	id exposure_any_0 exposure_any_1 exposure_any_2 exposure_any_3 exposure_any_4
     <int>          <num>          <num>          <num>          <num>          <num>
  1:     1              0              1              1             NA             NA
  2:     2              0              1              1              1              1
  3:     3              0              1              1              1              1
  4:     4              0              0              1              1              1
  5:     5              1              1              1             NA             NA
  6:     6              1              1             NA             NA             NA
     exposure_any_5
	      <num>
  1:             NA
  2:              1
  3:              1
  4:              1
  5:             NA
  6:             NA

  $exposure_percent
  Key: <id>
	id exposure_percent_0 exposure_percent_1 exposure_percent_2 exposure_percent_3
     <int>              <num>              <num>              <num>              <num>
  1:     1                  0          0.7189525           0.218460                 NA
  2:     2                  0          0.4607913           1.000000                  1
  3:     3                  0          0.2167236           1.000000                  1
  4:     4                  0          0.0000000           0.973679                  1
  5:     5                  1          1.0000000           1.000000                 NA
  6:     6                  1          1.0000000                 NA                 NA
     exposure_percent_4 exposure_percent_5
		  <num>              <num>
  1:                 NA                 NA
  2:                  1          0.9147968
  3:                  1          0.8877856
  4:                  1          0.7720416
  5:                 NA                 NA
  6:                 NA                 NA

  $exposure_time
  Key: <id>
	id exposure_time_0 exposure_time_1 exposure_time_2 exposure_time_3 exposure_time_4
     <int>           <num>           <num>           <num>           <num>           <num>
  1:     1               0       2.8758101       0.8738402              NA              NA
  2:     2               0       1.8431654       4.0000000               4               4
  3:     3               0       0.8668944       4.0000000               4               4
  4:     4               0       0.0000000       3.8947160               4               4
  5:     5               1       4.0000000       4.0000000              NA              NA
  6:     6               1       4.0000000              NA              NA              NA
     exposure_time_5
	       <num>
  1:              NA
  2:        3.659187
  3:        3.551143
  4:        3.088166
  5:              NA
  6:              NA

  $exposure_threshold
  Key: <id>
	id exposure_threshold_0 exposure_threshold_1 exposure_threshold_2 exposure_threshold_3
     <int>                <num>                <num>                <num>                <num>
  1:     1                    0                    1                    0                   NA
  2:     2                    0                    0                    1                    1
  3:     3                    0                    0                    1                    1
  4:     4                    0                    0                    1                    1
  5:     5                    0                    1                    1                   NA
  6:     6                    0                    1                   NA                   NA
     exposure_threshold_4 exposure_threshold_5
		    <num>                <num>
  1:                   NA                   NA
  2:                    1                    1
  3:                    1                    1
  4:                    1                    1
  5:                   NA                   NA
  6:                   NA                   NA
  #+end_example

  NB: When exposure start at time 0, we should be careful with
  =exposure_time= and =exposure_percent= because the duration window
  here has length 0, so these methods can behave weirdly. For
  instance, subjects that start exposure at time zero will have
  exposure time equal to 1 at time 0 (no matter the underlying time
  scale). Maybe this should be changed.


* To do's

- [X] Document all different methods
- [X] Use how to construct different variable wide variables from same
  long variable
- [ ] Check with TAG that he agrees
- [ ] Add sketch for how to add the used long_to_wide methods to the
  rtmle object

Later
- [ ] Add description in the documentation of =long_to_wide= function
  itself or refer to this vignette from there.
- [ ] Documenting writing own function
- [ ] What to do about threshold if grid is not equidistant?
- [ ] Figure out if below is a bug or a feature, and provide better
  documentation of the duration based methods when
  #+BEGIN_SRC R
    # People who start exposure at time 0 have exposure_time==1 at exposure_0:
    x$long_data$timevar_data$exposure[id == 5]
    x <- long_to_wide(x, exposure = list(method = "exposure_time"))
    x$data$timevar_data$exposure[id == 5]
  #+END_SRC
