* About

The R-package =rtmle= implements a class of targeted minimum loss
estimators for the analysis of longitudinal register data. The
functionality is similar to the established R-package =ltmle= with the
following features and focus points:

- explicit handling of competing risks
- polypharmacy
- descriptive statistics
- diagnostic tools (not to be confused with model goodness of fit)
- subgroup analysis
- support for glmnet
- cheap bootstrap inference
- cross-fitting 
- parallel computing

* Data structures  

We consider register data in the following format.

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes
library(rtmle)
library(prodlim)
library(riskRegression)
library(data.table)
set.seed(118)
ld <- simulate_long_data(n = 10000,number_visits = 20,beta = list(sum_A_on_Y = -.1,A0_on_Y = 0),register_format = TRUE)
ld
#+END_SRC

#+RESULTS[(2025-04-10 11:48:17) fbea64b41ce76f4479ef4368ff8f2f1cda31c3b2]:
:results:
$baseline_data
          id   sex      age
       <int> <int>    <num>
    1:     1     0 59.44409
    2:     2     1 73.01360
    3:     3     0 78.26086
    4:     4     1 66.53408
    5:     5     0 62.35921
   ---                     
 9996:  9996     0 43.90035
 9997:  9997     1 41.32339
 9998:  9998     0 65.08893
 9999:  9999     1 42.23665
10000: 10000     1 57.38959

$timevar_data
$timevar_data$L
         id   date
      <int>  <num>
   1:     1   0.00
   2:     3   0.00
   3:     5   0.00
   4:     8   0.00
   5:    14   0.00
  ---             
5119:  9988 421.80
5120:  9992 355.43
5121:  9995 246.33
5122:  9998 377.86
5123:  9998 483.76

$timevar_data$A
         id  date
      <int> <num>
   1:     1     0
   2:     3     0
   3:     5     0
   4:     7     0
   5:     9     0
  ---            
5249:  9590   365
5250:  9671   365
5251:  9694   365
5252:  9859   365
5253:  9984   730


$outcome_data
         id    date
      <int>   <num>
   1:     1 1076.89
   2:     3   50.49
   3:     6  140.84
   4:     7  402.61
   5:    11  481.58
  ---              
3341:  9979   60.41
3342:  9990   31.30
3343:  9993   19.82
3344:  9998  609.26
3345:  9999    8.99

$competing_data
         id   date
      <int>  <num>
   1:     4  89.71
   2:     8  91.81
   3:    10 545.28
   4:    13 446.94
   5:    14 459.49
  ---             
3360:  9987  30.28
3361:  9988 476.90
3362:  9994 311.22
3363:  9996  71.81
3364:  9997 179.60

$censored_data
         id    date
      <int>   <num>
   1:     2  260.64
   2:     5    6.32
   3:     9  209.74
   4:    25  298.93
   5:    33  341.00
  ---              
3287:  9989   53.65
3288:  9991  392.38
3289:  9992 1046.23
3290:  9995  758.63
3291: 10000  140.10
:end:

* Example


** Initializing


#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer :exports both  :session *R* :cache yes  
x <- rtmle_init(intervals = 3,name_id = "id",name_outcome = "Y",name_competing = "Dead",name_censoring = "Censored",censored_label = "censored")
x
#+END_SRC

#+RESULTS[(2025-04-10 11:48:17) 8b507b232db5bb073a8147380c6d781f9e76f9f1]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no data yet.
Add the baseline data (if any) with the function 'add_baseline_data<-'
Add the outcome data and the longitudinal data (covariates and treatment) with one of the functions
: 'add_long_data<-' or 'add_wide_data<-'.
TODO: The object contains no protocols. Add them with the function 'protocol<-'.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Adding the data

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
x$long_data <- ld[c("outcome_data","censored_data","competing_data","timevar_data")]
add_baseline_data(x) <- ld$baseline_data[,start_followup_date:=0]
x
#+END_SRC

#+RESULTS[(2025-04-10 11:48:17) 49bdcfec7b8159dc23005a1d326989b56a4547c1]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no protocols. Add them with the function 'protocol<-'.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Preparing the data

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
x <- long_to_wide(x,intervals = seq(0,2000,30.45*6))
prepare_data(x) <- list()
x$prepared_data
#+END_SRC

#+RESULTS[(2025-04-10 11:48:18) 824e49ea434194f42fc103b764371428d538b5fb]:
:results:
id   sex      age start_followup_date   L_0   A_0 Censored_1   Y_1 Dead_1   L_1   A_1 Censored_2   Y_2 Dead_2   L_2   A_2 Censored_3
       <int> <int>    <num>               <num> <num> <num>     <fctr> <num>  <num> <num> <num>     <fctr> <num>  <num> <num> <num>     <fctr>
    1:     1     0 59.44409                   0     1     1 uncensored     0      0     0     0 uncensored     0      0     0     0 uncensored
    2:     2     1 73.01360                   0     0     0 uncensored     0      0     0     0   censored    NA     NA    NA    NA       <NA>
    3:     3     0 78.26086                   0     1     1 uncensored     1      0    NA    NA       <NA>     1      0    NA    NA       <NA>
    4:     4     1 66.53408                   0     0     0 uncensored     0      1    NA    NA       <NA>     0      1    NA    NA       <NA>
    5:     5     0 62.35921                   0     1     1   censored    NA     NA    NA    NA       <NA>    NA     NA    NA    NA       <NA>
   ---                                                                                                                                        
 9996:  9996     0 43.90035                   0     0     0 uncensored     0      1    NA    NA       <NA>     0      1    NA    NA       <NA>
 9997:  9997     1 41.32339                   0     0     0 uncensored     0      1    NA    NA       <NA>     0      1    NA    NA       <NA>
 9998:  9998     0 65.08893                   0     1     1 uncensored     0      0     0     0 uncensored     0      0     0     0 uncensored
 9999:  9999     1 42.23665                   0     0     1 uncensored     1      0    NA    NA       <NA>     1      0    NA    NA       <NA>
10000: 10000     1 57.38959                   0     1     0   censored    NA     NA    NA    NA       <NA>    NA     NA    NA    NA       <NA>
         Y_3
       <num>
    1:     0
    2:    NA
    3:     1
    4:     0
    5:    NA
   ---      
 9996:     0
 9997:     0
 9998:     0
 9999:     1
10000:    NA
:end:


** Defining the protocols

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
protocol(x) <- list(name = "always A",treatment_variables = "A",intervention = 1)
protocol(x) <- list(name = "never A",treatment_variables = "A",intervention = 0)
x
#+END_SRC

#+RESULTS[(2025-04-10 11:48:18) c33c12a3fb685d3e26c9888a929f778ad970845e]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
TODO: The object contains no targets yet. Add them with the function 'target<-'.
:end:


** Defining the targets

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer  :exports both  :session *R* :cache yes  
target(x) <- list(name = "Outcome_risk",strategy = "additive",estimator = "tmle",time_horizon = 3,protocols = c("always A","never A"))
x
#+END_SRC

#+RESULTS[(2025-04-10 11:48:18) 9e87d956cc3fa23e94cb0e46e5c41ada18451329]:
:results:
Targeted minimum loss analysis of register data.
  Initialized to 3 time intervals (starting at time zero).
  The name of the subject id variable is 'id'.
  The outcome, competing risk and censoring variables are named 'Y', 'Dead', and 'Censored', respectively.
:end:

** Sequential regression with and without TMLE update step

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer :exports both  :session *R* :cache yes
x <- run_rtmle(x,learn = "learn_glm")
#+END_SRC

#+RESULTS[(2025-04-10 11:48:19) f4b6ba5c87a4fcdc5adb0f95cc42bbc7a591718f]:
:results:
Running target: Outcome_risk... Set argument verbose = FALSE to suppress this message.
Current protocol: always A ... Set argument verbose = FALSE to suppress this message.
Current protocol: never A ... Set argument verbose = FALSE to suppress this message.
Warning messages:
1: In tmle_update(Y = Y, offset = W_previous, intervention_probs = inverse_probability_weights,  :
  No TMLE update because no subject has positive weight
2: In tmle_update(Y = Y, offset = W_previous, intervention_probs = inverse_probability_weights,  :
  No TMLE update because no subject has positive weight
:end:

#+ATTR_LATEX: :options otherkeywords={}, deletekeywords={}
#+BEGIN_SRC R  :results output verbatim drawer :exports both  :session *R* :cache yes
summary(x)
#+END_SRC

#+RESULTS[(2025-04-10 11:48:19) ed7f60068378803177c2f5dd0741b7b6f64e7766]:
:results:
         Target Protocol Target_parameter Time_horizon Estimator   Estimate     P_value Standard_error        Lower       Upper
         <fctr>   <fctr>           <fctr>        <int>    <fctr>      <num>       <num>          <num>        <num>       <num>
1: Outcome_risk always A             Risk            3      tmle 0.33494029 1.000000000    0.004767184 -0.009343509 0.009343509
2: Outcome_risk  never A             Risk            3      tmle 0.35940602 1.000000000    0.007959865 -0.015601048 0.015601048
3: Outcome_risk  never A  Risk_difference            3      tmle 0.02446573 0.008367565    0.009278332  0.006280530 0.042650922
4: Outcome_risk  never A       Risk_ratio            3      tmle 1.07304504 0.007408370    0.026326689  1.019080828 1.129866854
   Estimate (CI_95)
             <char>
1:   33.5 [0.0;0.9]
2:   35.9 [0.0;1.6]
3:    2.4 [0.6;4.3]
4:    1.1 [1.0;1.1]
:end:


#+TITLE: Introduction to the R-package rtmle
#+Author: Thomas Alexander Gerds
#+Date: 
#+EMAIL: tag@biostat.ku.dk
#+LaTeX_CLASS: org-article
#+OPTIONS: H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS: TeX:t LaTeX:t skip:nil d:t todo:t pri:nil tags:not-in-toc author:nil
#+LaTeX_HEADER:\usepackage{authblk}
#+LaTeX_HEADER:\usepackage{natbib}
#+LaTeX_HEADER:\author{Thomas Alexander Gerds}
#+LaTeX_HEADER:\affil{Department of Biostatistics, University of Copenhagen}
#+set: superman-org-export-target: html

