#+TITLE: Data Preparation Workflow in rtmle
#+AUTHOR: Anders Munch
#+OPTIONS: num:nil toc:nil ^:nil
#+PROPERTY: header-args:R :async :results output :exports both :session *R* :cache yes
* notes                                                            :noexport:

FIX:
- [X] _init should not need anything else than outcome data by default
- [X] add_long_data should not demand anything:
- [X] Add functionality that allows adding timevar by name or by list
- [ ] fix date/time naming.

Think about summary functions. Look at long_to_wide.
- [ ] Write functionality with some predefined summarises. But look at
  what is done first. Think like this: What does the data we
  receive/use originally look like? Look at the LEADER
  data.

- Why need intervals in _init?

- In LEADER study we work directly on pre-descritized
  datasets. Include that as an example.

Structure:
- initialize the rtmle object
- add baseline data
- add time-varying data: Something about the structure of them and how
  to transform this type of data. And also something about both using
  the and wide data.  
- add protocols (later vignette?)


* Sandbox                                                          :noexport:

#+BEGIN_SRC R
  devtools::install()
  devtools::load_all()
  diab_data <- fread("./data/diabetes_sim_data.csv")

  ## Number of 6mth intervals in 3 years
  intervals <- 3
  time_grid <- seq(0, intervals*6, by = 6)

  ## Init
  x <- rtmle_init(intervals = intervals,
		  name_id = "id",
		  ## name_time = "time",  ## Later, should fix this
		  ## name_competing = "death",
		  name_outcome = "MACE")

  ## Baseline are variables that do change over time. Here, age is age
  ## at baseline
  x <- add_baseline_data(x,data=diab_data[time == 0, .(id, sex, age)])

  ## Time-varying covariates are variables may change over time and are not outcomes


  diab_data[event == "MACE",.(id,date = time)][!duplicated(id)]
  diab_data[event == "death",.(id,date = time)]
  ## diab_data[last == 1 &event %in% c("visit","dropout"),.(id,date = time)]

  diab_data[event%in%c("baseline","MACE","visit"),.(id, date = time, HbA1c)]

  tv_covs <- c("HbA1c","changeHbA1c","GLP1","SGLT2","DPP4","History_GLP1","History_SGLT2","History_DPP4")
      tv <- lapply(tv_covs, function(tv){
	  if (tv %in% c("GLP1","SGLT2","DPP4")){
	      d <- diab_data[,c("id","time",tv),with = FALSE]
	      setnames(d,c("id","start_exposure","value"))
	      d[,end_exposure := shift(x = start_exposure,n = 1,type = "lead"),by = id]
	      # when treatment starts at the last time point in a time-series
	      # then the duration is unknown
	      d <- d[!is.na(end_exposure)]
	      d <- d[value != 0]
	      d[,value := NULL]
	  }else{
	      d <- diab_data[event%in%c("baseline","MACE","visit"),c("id","time",tv),with = FALSE]
	      setnames(d,c("id","date","value"))
	  }
	  d[]
      })   
  names(tv) <- tv_covs

  ## Get first MACE event time for each id
  outcome_data <- diab_data[event == "MACE", .(date = min(time)), by = id]

  x1 <- add_long_data(x, timevar_data = tv[1])
  x2 <- add_long_data(x, HbA1c = tv[["HbA1c"]])
  identical(x1, x2)

  x <- add_long_data(x, outcome_data = outcome_data)
  x <- add_long_data(x, timevar_data = tv[1], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)
  x <- add_long_data(x, timevar_data = tv[1], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)
  y <- add_long_data(x, timevar_data = tv[1], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)




  x <- add_long_data(x, outcome_data = outcome_data, timevar_data = NULL, censored_data = NULL, competing_data = NULL)
  x <- add_long_data(x, timevar_data = tv[1], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)
  x <- add_long_data(x, timevar_data = tv[2], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)
  x <- add_long_data(x, timevar_data = tv[3], outcome_data = outcome_data, censored_data = NULL, competing_data = NULL)

  x <- long_to_wide(x,breaks = time_grid,start_followup_date = 0)

  ## Fix something about date/time internal naming.

  add_long_data(x, outcome_data = outcome_data, timevar_data = NULL, censored_data = NULL)

  diab_data[event == "MACE", .(id, time)]


#+END_SRC



* Overview

The rtmle package follows a stateful object-modification workflow:
1. Initialize an analysis object.
2. Add data components (baseline, wide, long).
3. Convert formats if needed.
4. Prepare the object for estimation.

This separates data engineering from causal modeling and estimation.

We illustrate using the dataset `diabetes_population`.

* Setup

We use

#+BEGIN_SRC R
  library(data.table)
  library(rtmle)
  diab_data <- fread("./data/diabetes_sim_data.csv")
#+END_SRC

#+RESULTS[384684746c78bfd0b35c54c9d3c89dcb8da7647b]:

#+BEGIN_SRC R 
head(diab_data)
#+END_SRC

#+RESULTS[90d024ba5cac58ccab5f05c5b741b8190c9a8dce]:
#+begin_example
      id      time    event   sex      age   HbA1c  MACE changeHbA1c  GLP1 SGLT2  DPP4
   <int>     <num>   <char> <int>    <num>   <num> <int>       <num> <int> <int> <int>
1:     1  0.000000 baseline     1 57.90114 47.8233     0   0.0000000     1     0     0
2:     1  5.158776    visit     1 57.90114 47.8233     0   0.6119453     1     0     1
3:     1 12.936978    visit     1 57.90114 47.8233     0  -0.5831727     0     0     0
4:     1 17.518595    visit     1 57.90114 47.8233     0   0.5532361     0     0     0
5:     1 24.667315    visit     1 57.90114 47.8233     0  -0.5534818     1     1     1
6:     1 31.123511    visit     1 57.90114 47.8233     0  -1.1469779     1     0     1
   History_SGLT2 History_GLP1 History_DPP4
           <int>        <int>        <int>
1:             0            0            0
2:             0            1            1
3:             0            1            1
4:             0            1            1
5:             1            2            2
6:             1            3            3
#+end_example

* Initialize

#+BEGIN_SRC R
  x <- rtmle_init(intervals = 3,
		  name_id = "id",
		  name_competing = "death",
		  name_outcome = "MACE",
		  name_censoring = "censoring")
#+END_SRC

* Add baseline data

* Add outcome(s) data

Information on outcome, competing event, and censoring. 

* Variable Types in diabetes_population

- Baseline (time-invariant): U, sex, age
- Time-varying covariates (L_t): HbA1c, changeHbA1c
- Treatments (A_t): GLP1, SGLT2, DPP4
- Outcome (Y_t): MACE
- Treatment summaries: History_GLP1, History_SGLT2, History_DPP4

* Step 1: Initialize

#+BEGIN_SRC r
library(rtmle)

rt_obj <- rtmle_init(
  id = "id",
  time = "time",
  event = "event"
)
#+END_SRC

* Step 2: Add Baseline Data

#+BEGIN_SRC r
rt_obj <- add_baseline_data(
  rt_obj,
  data = diabetes_population[diabetes_population$time == 0, ],
  baseline_vars = c("U", "sex", "age")
)
#+END_SRC

* Step 3: Add Wide Data

#+BEGIN_SRC r
rt_obj <- add_wide_data(
  rt_obj,
  data = diabetes_population[diabetes_population$time == 0, ],
  wide_vars = c("History_GLP1", "History_SGLT2", "History_DPP4")
)
#+END_SRC

* Step 4: Add Long Data

#+BEGIN_SRC r
rt_obj <- add_long_data(
  rt_obj,
  data = diabetes_population,
  time_varying_covariates = c("HbA1c", "changeHbA1c"),
  treatment_vars = c("GLP1", "SGLT2", "DPP4"),
  outcome_var = "MACE"
)
#+END_SRC

* Step 5: Convert Long to Wide

#+BEGIN_SRC r
wide_data <- long_to_wide(
  data = diabetes_population,
  id = "id",
  time = "time"
)
#+END_SRC

* Step 6: Prepare for Analysis

#+BEGIN_SRC r
rt_obj <- prepare_data(rt_obj)
#+END_SRC

After prepare_data(), the object is analysis-ready.
