library(testthat)
library(rtmle)
library(data.table)
library(prodlim)
test_that("run rtmle on simulated data",{
    set.seed(112)
    ld <- simulate_long_data(n = 91,number_visits = 20,beta = list(A_on_Y = -.2,A0_on_Y = -0.3,A0_on_A = 6),register_format = TRUE)
    x <- rtmle_init(intervals = 4,name_id = "id",name_outcome = "Y",name_competing = "Dead",name_censoring = "Censored",censored_label = "censored")
    x <- add_long_data(x,outcome_data=ld$outcome_data,censored_data=ld$censored_data,competing_data=ld$competing_data,timevar_data=ld$timevar_data)
    x <- add_baseline_data(x,data=ld$baseline_data)
    x <- long_to_wide(x,breaks = seq(0,2000,30.45*6),verbose = 0L)
    x <- protocol(x,name = "Always_A",treatment_variables = "A",intervention = 1)
    x <- prepare_data(x) 
    x <- target(x,name = "Outcome_risk",estimator = "tmle",protocols = "Always_A")
    x <- model_formula(x)
    suppressWarnings(x <- run_rtmle(x,time_horizon = 2,refit = TRUE,verbose = FALSE))
    expect_equal(x$estimate$Main_analysis$Estimate,0.1497072,tolerance = 0.001)
    expect_equal(x$estimate$Main_analysis$Standard_error,0.06217111,tolerance = 0.001)
})
test_that("run rtmle without covariates",{
    set.seed(112)
    ld <- simulate_long_data(n = 91,number_visits = 20,beta = list(A_on_Y = -.2,A0_on_Y = -0.3,A0_on_A = 6),register_format = TRUE)
    x <- rtmle_init(intervals = 4,name_id = "id",name_outcome = "Y",name_competing = "Dead",name_censoring = "Censored",censored_label = "censored")
    #  add treatment variables but no timevarying covariates
    x <- add_long_data(x,outcome_data=ld$outcome_data,censored_data=ld$censored_data,competing_data=ld$competing_data,timevar_data = ld$timevar_data["A"])
    #  need id variable in the baseline data
    x <- add_baseline_data(x,data=ld$baseline_data[,.(id)])
    x <- long_to_wide(x,breaks = seq(0,2000,30.45*6),verbose = 0L)
    x <- protocol(x,name = "Always_A",treatment_variables = "A",intervention = 1)
    x <- prepare_data(x) 
    x <- target(x,name = "Outcome_risk",estimator = "tmle",protocols = "Always_A")
    x <- model_formula(x)
    suppressWarnings(x <- run_rtmle(x,time_horizon = 2,refit = TRUE,verbose = FALSE))
    expect_equal(x$estimate$Main_analysis$Estimate,0.1388889,tolerance = 0.001)
    expect_equal(x$estimate$Main_analysis$Standard_error,0.05795775,tolerance = 0.001)
})
test_that("run rtmle without competing risks",{
    set.seed(112)
    ld <- simulate_long_data(n = 91,number_visits = 20,beta = list(A_on_Y = -.2,A0_on_Y = -0.3,A0_on_A = 6),register_format = TRUE)
    x <- rtmle_init(intervals = 2,name_id = "id",name_outcome = "Y",name_competing = NULL,name_censoring = "Censored",censored_label = "censored")
    x$long_data <- ld[c("outcome_data","censored_data","timevar_data")]
    x$long_data$outcome_data <- rbind(x$long_data$outcome_data,ld$competing_data)
    setkey(x$long_data$outcome_data,id,date)
    x <- add_baseline_data(x,data=ld$baseline_data)
    x <- long_to_wide(x,breaks = seq(0,2000,30.45*6),verbose = FALSE)
    x <- protocol(x,name = "Always_A",treatment_variables = "A",intervention = 1)
    x <- prepare_data(x,verbose = FALSE)     
    x <- target(x,name = "Outcome_risk",estimator = "tmle",protocols = "Always_A")
    x <- model_formula(x)
    suppressWarnings(x <- run_rtmle(x,verbose = FALSE))
    expect_output(print(summary(x)))
})

test_that("rtmle can use g-formula",{
    set.seed(112)
    ld <- simulate_long_data(n = 91,number_visits = 20,beta = list(A_on_Y = -.2,A0_on_Y = -0.3,A0_on_A = 6),register_format = TRUE)
    x <- rtmle_init(intervals = 2,name_id = "id",name_outcome = "Y",name_competing = NULL,name_censoring = "Censored",censored_label = "censored")
    x$long_data <- ld[c("outcome_data","censored_data","timevar_data")]
    x$long_data$outcome_data <- rbind(x$long_data$outcome_data,ld$competing_data)
    setkey(x$long_data$outcome_data,id,date)
    x <- add_baseline_data(x,data=ld$baseline_data)
    x <- long_to_wide(x,breaks = seq(0,2000,30.45*6),verbose = FALSE)
    x <- protocol(x,name = "Always_A",treatment_variables = "A",intervention = 1)
    x <- prepare_data(x,verbose = FALSE)     
    x <- target(x,name = "Outcome_risk",protocols = "Always_A")
    x <- model_formula(x)
    x <- run_rtmle(x,estimator = "tmle",verbose = FALSE)
    x$protocols$Always_A$cumulative_intervention_probs <- pmax(x$protocols$Always_A$cumulative_intervention_probs,0.5)
    z <- run_rtmle(x,refit = FALSE,estimator = "tmle",verbose = FALSE)
    y <- run_rtmle(x,estimator = "g-formula",verbose = FALSE)
    expect_output(print(summary(x)))    
})


