#' Simulated cohort
#'
#' A longitudinal event-history cohort generated with \code{\link{simulate_cohort}}.
#' The cohort contains baseline covariates, repeated visits, treatment
#' assignments, intermediate events, and absorbing events. It is used in package
#' examples as compact input data for \code{\link{register_format}} and the
#' usual \code{rtmle} data preparation workflow.
#'
#' @format A \code{\link[data.table]{data.table}} with 5,442 rows and 11 columns:
#' \describe{
#'   \item{id}{Integer subject identifier.}
#'   \item{time}{Event or visit time on the simulated follow-up scale.}
#'   \item{event}{Factor identifying the row type: baseline, visit, bleeding,
#'   dropout, stroke, or death.}
#'   \item{age}{Baseline age.}
#'   \item{sex}{Baseline binary sex indicator.}
#'   \item{SBP}{Baseline systolic blood pressure.}
#'   \item{stroke}{Stroke event indicator.}
#'   \item{bleeding}{Bleeding event indicator.}
#'   \item{changeSBP}{Visit-level change in systolic blood pressure.}
#'   \item{A}{Visit-level binary treatment indicator.}
#'   \item{B}{Visit-level binary treatment indicator.}
#' }
#' The simulation call is stored in \code{attr(simulated_cohort, "call")}.
#'
#' @source Generated by \code{data-raw/generate_example_data.R}.
#' @keywords datasets
"simulated_cohort"

#' Fitted rtmle object
#'
#' A fitted \code{"rtmle"} analysis object built from
#' \code{simulated_cohort}. The object is prepared, has three treatment
#' protocols, and includes fitted nuisance models and main-analysis estimates at
#' time horizons 1 through 4.
#'
#' @format An object of class \code{"rtmle"} containing the usual analysis
#' components, including:
#' \describe{
#'   \item{prepared_data}{A wide analysis data set with 307 subjects and 38
#'   variables.}
#'   \item{protocols}{Three protocols: \code{"Always_A"}, \code{"Never_A"}, and
#'   \code{"Always_B"}.}
#'   \item{targets}{Two target definitions: \code{"Treatment effect"} and
#'   \code{"Treatment contrast"}.}
#'   \item{estimate}{Main-analysis risk estimates for time horizons 1 through 4.}
#'   \item{models}{Fitted nuisance-parameter models from
#'   \code{\link{run_rtmle}}.}
#'   \item{time_grid_labels}{Plot labels for the time-grid points.}
#' }
#'
#' @source Generated by \code{data-raw/generate_example_data.R}.
#' @keywords datasets
"rtmle_object"
