### make_exclusion_rule.R --- 
#----------------------------------------------------------------------
## Author: Thomas Alexander Gerds
## Created: Jul 22 2025 (09:06) 
## Version: 
## Last-Updated: Jul 22 2025 (09:18) 
##           By: Thomas Alexander Gerds
##     Update #: 2
#----------------------------------------------------------------------
## 
### Commentary: 
## 
### Change Log:
#----------------------------------------------------------------------
## 
### Code:
##' Create exclusion rules for model_formula
##'
##' Creates a named list of variables that should be excluded from formulas
##' generated by \code{\link{model_formula}}.
##'
##' @title Helper for model_formula exclusion rules
##' @param timepoint Maximum time point of interest.
##' @param name_outcome_variable Name of the time-dependent outcome, treatment,
##'   or censoring variable without its time suffix.
##' @param excluded_variables Vector of time-dependent variables, without time
##'   suffixes, to exclude.
##' @param recursive Logical. If \code{TRUE}, exclude all historical values of
##'   each variable; otherwise exclude only the value from the same time point.
##' @return A named list suitable for the \code{exclusion_rules} argument of
##'   \code{\link{model_formula}}.
##' @seealso \code{\link{model_formula}}
##' @examples
##' make_exclusion_rule(4,"A","B",recursive = TRUE)
##' make_exclusion_rule(4,"A",c("B","C"),recursive = TRUE)
##' @export 
##' @author Thomas A. Gerds <tag@@biostat.ku.dk>
make_exclusion_rule <- function(timepoint,name_outcome_variable,excluded_variables,recursive = FALSE){
    timepoints <- 0:timepoint
    erule <- lapply(0:timepoint,function(tp){
        suffix <- if(recursive) 0:tp else tp
        unlist(lapply(excluded_variables,function(ev){paste0(ev,"_",suffix)}),use.names = FALSE)
    })
    names(erule) <- paste0(name_outcome_variable,"_",0:timepoint)
    erule
}


######################################################################
### make_exclusion_rule.R ends here
