# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

split2 <- function(pnrnum, inn, out, event, mergevar, split, numcov) {
    .Call(`_rtmle_split2`, pnrnum, inn, out, event, mergevar, split, numcov)
}

#' @export
splitdate <- function(inn, out, event, mergevar, seq, varname) {
    .Call(`_rtmle_splitdate`, inn, out, event, mergevar, seq, varname)
}

splitft <- function(pnrnum, inn, out, event, mergevar, Spnrnum, val, start, end, num, numcov, default_) {
    .Call(`_rtmle_splitft`, pnrnum, inn, out, event, mergevar, Spnrnum, val, start, end, num, numcov, default_)
}

